configVersion: 1.0.0
componentName: tcpip_basic_config
coreVersion: 5.8.4
device: PIC32MZ2048EFM100
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: tcpip_basic_config
  type: module
  version: ''
- dependencyPackage: ''
  name: net
  type: package
  version: v3.14.4
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition: {}
  symbols:
    TCPIP_AUTOCONFIG_ENABLE_NETCONFIG:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_NETCONFIG
      children:
      - children:
        - attributes:
            id: udp_bootloader
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    TCPIP_AUTOCONFIG_ENABLE_STACK:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_STACK
      children:
      - children:
        - attributes:
            id: tcpip_basic_config
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
  userData: {}
